version: '3'
services:
  
  mongo-server:
    image: 'mongo:latest'
    ports:
      - 27017:27017

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - MONGO_HOST=mongodb://mongo-server
      - SERVER_PORT=8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 8081:8081
    environment:
      - BASE_URL=http://localhost:8080
      - CONTEXT_PATH=todoApp

  nginx: 
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    restart: always

    